[package]
name = "cork"
version = "0.1.0"
authors = ["Deep Majumder <deep.majumder2019@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
pest = "2.1.3"
pest_derive = "2.1.0"
home = "0.5.3"
lazy_static = "1.4.0"
